# Onshape_Caster

## Part 1 - Base

Rectangle 200 x 120 mm.  10 mm holes, 20 mm from each edge.  Try using a linear pattern.  25 mm hole 60 mm from one side.

<img src="/media/base.png" width="300px">

https://youtu.be/rKfAlTlEstI

## Part 2 - Mount

Almost all of the same geometry as the previous part.  But this part is a 120 mm x 120 mm square.  _Make it in the same Part Studio as the base._

<img src="/media/mount.png" width="300px">

https://youtu.be/d8cwE17IluY

## Part 3 - Fork

Start with a 80 mm circle, extruded 8 mm thick.  Then a 40 mm x 5 mm rectangle, 15 mm from the center.  Extrude that 75mm.  Then add 15 mm fillets to the top.  Some more 1 mm images to smooth things out.  Mirror that.  Then poke a 10 mm hole through the fork legs, 15 mm from the top.  A 60 mm tube on the other side, 15 mm ID, 20 mm OD.  Finally, a 1 mm chamfer.

<img src="/media/fork.png" width="300px">

https://youtu.be/NdAtfCPoKEY

